### ISSUE TITLE
Plugin broken in WordPress 4.4

### ISSUE THREAD

**Issue by frankiejarrett** [fjarrett/compact-view-mode#3]
Reported: https://wordpress.org/support/topic/not-working-1512?replies=3

Caused by: https://core.trac.wordpress.org/changeset/35357

In WordPress 4.4 the view mode controls were moved to the Screen Options. Additionally, the view mode is now honored by any hierarchical post type with a visible UI.

**Comment by tsvetnoff** [comment]
As a temporary relation I added 2 rows in admin CSS:
.row-actions {float: right !important;}
.column-title strong {float: left !important;}
Maybe would be helpful for you.
That's the result: https://drive.google.com/file/d/0B4WgWARUBTsZOFpmMXM4RmZ3cFk/view?usp=sharing

**Comment by frankiejarrett** [comment]
Hey thanks for sharing @tsvetnoff. Floating right definitely looks good when columns have been removed, but it does not wrap cleanly when more columns are present and a long title is used.

<img width="576" alt="screen shot 2015-12-20 at 4 07 54 pm" src="https://cloud.githubusercontent.com/assets/522158/11920397/da377688-a733-11e5-9185-c0fb0af3fbe3.png">

**Comment by tsvetnoff** [comment]
Yes, it is. But if you will change words to icons it would be fine. Also maybe to cut words "Published" and "Last Modified" from Date column and keep only numbers "12/20/2015". Is it difficult?
